categories:
  vouchers:
    label: 'LLL:EXT:products_voucher/Resources/Private/Language/locallang_settings.xlf:category.vouchers'
    parent: products

settings:
  products.vouchers.gained.enabled:
    type: bool
    default: false
    label: 'LLL:EXT:products_voucher/Resources/Private/Language/locallang_settings.xlf:setting.products.vouchers.gained.enabled'
    category: vouchers
  products.vouchers.gained.minimumOrderValue:
    type: number
    default: 0.00
    label: 'LLL:EXT:products_voucher/Resources/Private/Language/locallang_settings.xlf:setting.products.vouchers.gained.minimumOrderValue'
    category: vouchers
  products.vouchers.gained.rewardType:
    type: string
    default: 'fixed'
    label: 'LLL:EXT:products_voucher/Resources/Private/Language/locallang_settings.xlf:setting.products.vouchers.gained.rewardType'
    category: vouchers
  products.vouchers.gained.rewardValue:
    type: number
    default: 5.00
    label: 'LLL:EXT:products_voucher/Resources/Private/Language/locallang_settings.xlf:setting.products.vouchers.gained.rewardValue'
    category: vouchers
